spring.application.name=bills_reimbursement

# MySQL Database Connection Settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.config.import=optional:file:.env[.properties]

# JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=uploads/